services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaia_db
      MYSQL_USER: enzo
      MYSQL_PASSWORD: Enziitho13579
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-henv", "db", "-uenzo", "-pEnziitho13579"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
